---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: ./cmd/autowyze/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/autowyze
    username:
      from_secret: quay_username

...
