pipeline:
  quay:
    image: plugins/docker
    repo: quay.io/jonnrb/autowyze
    username: $QUAY_USERNAME
    password: $QUAY_PASSWORD
    dockerfile: ./cmd/autowyze/Dockerfile
    storage_driver: overlay2
